### ISSUE TITLE
Double bug in one game

### ISSUE THREAD

**Issue by theofficialblx** [Sergetec/Wrdl-Bot#2]
1. The qajaq guess bugged out of the screen. Noticed happens after almost all Qs if it’s black.
2. My fifth guess, metre, was supposed to show that both Es are yellow since the correct word is erect, making it impossible to win the game by the rules.

Screenshot attached.
![image](https://github.com/Sergetec/Wrdl-Bot/assets/108845186/602b3090-70bb-4b46-b6b0-6f4552376f0c)

**Comment by sergiulefter** [comment]
Thank you for reporting these issues. I just pushed an update that fixes both of these bugs:

1. The display issue with any word that contains a black Q (the word doesn't contain Q), now it is displaying correctly.
2. The problem with the duplicate letter hints, now if a word has duplicate letters like metre, a guess containg 2 E's in the wrong place should return both of them yellow and so on.
