### ISSUE TITLE
Words used etc on bottom qwerty domnotmahow properly.

### ISSUE THREAD

**Issue by LazeTheos** [Sergetec/Wrdl-Bot#3]
The letters used, in wrong place and letters correct spot shown incorrect on the key card below it. It's doing it as an a through an keyboard instead qwerty

![Screenshot_20240620-180428](https://github.com/Sergetec/Wrdl-Bot/assets/109141409/8c2c2b29-cdff-4525-a0e7-70bdc6fbcdf2)

**Comment by sergiulefter** [comment]
Thanks for reporting this bug, just pushed an update to the bot and I think that everything should be fixed now.
