### ISSUE TITLE
/stats gives error

### ISSUE THREAD

**Issue by MohamedAfraz** [Sergetec/Wrdl-Bot#4]
Running `/stats` on the WRDL Bot gives   <br>
```The application did not respond error```

Is this a client side error or a server side one?

How can i get a fix?

**Comment by sergiulefter** [comment]
Thanks for the heads up, I am investigating the error and will come back with a fix

**Comment by sergiulefter** [comment]
Thanks for reporting this bug, just pushed an update to the bot and I think that everything should be fixed now.
